<a href="https://colab.research.google.com/github/Rafifh7/Machine-Learning/blob/main/Week9_Concise_Implementation_of_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install d2l==0.17.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 83 kB 629 kB/s 


In [2]:
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)
def load_array(data_arrays, batch_size, is_train=True):  #@save
    """Construct a TensorFlow data iterator."""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[ 1.7454873 , -2.8956523 ],
        [ 1.4361072 ,  1.2283247 ],
        [-0.28149375, -1.3137449 ],
        [-1.3691933 , -0.08922743],
        [ 0.74933517,  1.9374768 ],
        [ 0.28554863,  0.75655115],
        [ 0.7994991 , -1.2899337 ],
        [-0.1517061 , -0.84313285],
        [ 0.530321  ,  0.45528504],
        [ 2.1266625 ,  1.0494981 ]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[17.55478   ],
        [ 2.902009  ],
        [ 8.079229  ],
        [ 1.7707504 ],
        [-0.87957793],
        [ 2.1938808 ],
        [10.177592  ],
        [ 6.746984  ],
        [ 3.7004814 ],
        [ 4.878735  ]], dtype=float32)>)

In [3]:
# `keras` is the high-level API for TensorFlow
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))
loss = tf.keras.losses.MeanSquaredError()
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

In [4]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000214
epoch 2, loss 0.000096
epoch 3, loss 0.000096


In [5]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([ 0.00060678 -0.00052881], shape=(2,), dtype=float32)
error in estimating b [0.00017405]
